version: '3'

services:
  mysql:
    image: mysql:8.4
    container_name: mysql-clean-arch
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: orders
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - .docker/mysql:/var/lib/mysql
      - ./configs/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - clean-arch-network  
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-clean-arch
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - clean-arch-network
  app:
    build: .
    depends_on:
      - mysql
      - rabbitmq
    command: go run main.go wire_gen.go
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: orders
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USER: guest
      RABBITMQ_PASSWORD: guest
    volumes:
      - .:/app
    working_dir: /app/cmd/ordersystem
    ports:
      - "8000:8000"
      - "50051:50051"
      - "8080:8080"
    networks:
      - clean-arch-network  

networks:
  clean-arch-network:
    driver: bridge      